import { Fragment } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Card from './../components/Card'

export default function Home () {
  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* NAV BAR */}
      <Card />
    </Fragment>
  )
}
