import { Fragment } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Card from './../components/Card/Card'

export default function Home () {
  return (
    <Fragment>
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link
          href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'
          rel='stylesheet'
          integrity='sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x'
          crossorigin='anonymous'
        />
      </Head>
      {/* NAV BAR */}
      <Card />
    </Fragment>
  )
}
